name: Maven CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 11

      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Pick maven version
        run: mvn wrapper:wrapper -Dmaven=3.8.6
      - name: Build project with Maven
        run: ./mvnw -B package

  publish-job:
    runs-on: ubuntu-latest
    needs: [ build_and_test ]
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 11
      - name: Pick maven version
        run: mvn wrapper:wrapper -Dmaven=3.8.6
      - name: Bump Version
        id: bump
        uses: Plugily-Projects/maven-version-bump-action@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-version-bump: true
          git-committer: 'BOT'
      - run: ./mvnw -B package -DskipTests
      - run: mkdir staging && cp target/*jar-with-dependencies.jar staging
      - name: Publish package
        run: ./mvnw --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging